#rkalluru/kb04-env:v1 
FROM centos 
ENV a=100 
## ENV can allow you to access a variable during the build of image.
RUN echo $a 
## ENV will also add this env variable inside the container as well and when you run container then you can access this variable.
