#rkalluru/kb04-copy:v1
FROM centos 
COPY sample.txt /tmp 
## sample.txt file is in local localtion and hence it is able to copy 
## What if the file is in some other location 
#COPY /tmp/sample1.txt /tmp 
# The above statement will not work and docker build cannot copy files from elsewhere other than this location


